//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.24 at 10:37:34 AM CEST 
//


package APIs.packageAssign;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriberAPIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriberAPIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubscriberPackageAssign" type="{}SubscriberPackageAssignType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriberAPIType", propOrder = {
    "version",
    "subscriberPackageAssign"
})
public class SubscriberAPIType {

    @XmlElement(required = true)
    protected String version;
    @XmlElement(name = "SubscriberPackageAssign", required = true)
    protected SubscriberPackageAssignType subscriberPackageAssign;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the subscriberPackageAssign property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriberPackageAssignType }
     *     
     */
    public SubscriberPackageAssignType getSubscriberPackageAssign() {
        return subscriberPackageAssign;
    }

    /**
     * Sets the value of the subscriberPackageAssign property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriberPackageAssignType }
     *     
     */
    public void setSubscriberPackageAssign(SubscriberPackageAssignType value) {
        this.subscriberPackageAssign = value;
    }

}
