//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.24 at 10:37:34 AM CEST 
//


package APIs.packageAssign;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriberPackageAssignType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriberPackageAssignType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subscriberPackage" type="{}subscriberPackageType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriberPackageAssignType", propOrder = {
    "subscriberPackage"
})
public class SubscriberPackageAssignType {

    @XmlElement(required = true)
    protected SubscriberPackageType subscriberPackage;

    /**
     * Gets the value of the subscriberPackage property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriberPackageType }
     *     
     */
    public SubscriberPackageType getSubscriberPackage() {
        return subscriberPackage;
    }

    /**
     * Sets the value of the subscriberPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriberPackageType }
     *     
     */
    public void setSubscriberPackage(SubscriberPackageType value) {
        this.subscriberPackage = value;
    }

}
