//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.24 at 11:03:06 AM CEST 
//


package APIs.packageUnassign;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for packageDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="packageDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="packageId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="packageLocked" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="usoc" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="packageRateCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subscriptionStartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subscriptionEndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "packageDataType", propOrder = {
    "packageId",
    "packageLocked",
    "usoc",
    "packageRateCode",
    "subscriptionStartDate",
    "subscriptionEndDate"
})
public class PackageDataType {

    protected String packageId;
    protected String packageLocked;
    protected String usoc;
    @XmlElement(required = true)
    protected String packageRateCode;
    @XmlElement(required = true)
    protected String subscriptionStartDate;
    @XmlElement(required = true)
    protected String subscriptionEndDate;

    /**
     * Gets the value of the packageId property.
     * 
     */
    public String getPackageId() {
        return packageId;
    }

    /**
     * Sets the value of the packageId property.
     * 
     */
    public void setPackageId(String value) {
        this.packageId = value;
    }

    /**
     * Gets the value of the packageLocked property.
     * 
     */
    public String getPackageLocked() {
        return packageLocked;
    }

    /**
     * Sets the value of the packageLocked property.
     * 
     */
    public void setPackageLocked(String value) {
        this.packageLocked = value;
    }

    /**
     * Gets the value of the usoc property.
     * 
     */
    public String getUsoc() {
        return usoc;
    }

    /**
     * Sets the value of the usoc property.
     * 
     */
    public void setUsoc(String value) {
        this.usoc = value;
    }

    /**
     * Gets the value of the packageRateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageRateCode() {
        return packageRateCode;
    }

    /**
     * Sets the value of the packageRateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageRateCode(String value) {
        this.packageRateCode = value;
    }

    /**
     * Gets the value of the subscriptionStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionStartDate() {
        return subscriptionStartDate;
    }

    /**
     * Sets the value of the subscriptionStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionStartDate(String value) {
        this.subscriptionStartDate = value;
    }

    /**
     * Gets the value of the subscriptionEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionEndDate() {
        return subscriptionEndDate;
    }

    /**
     * Sets the value of the subscriptionEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionEndDate(String value) {
        this.subscriptionEndDate = value;
    }

}
